### ISSUE TITLE
Plugin doesn't seem to work with `@angular/cdk/bidi` 

### ISSUE THREAD

**Issue by jarek104** [unindented/storybook-addon-rtl#10]
Toggling directionality using the plugin does not trigger the Direction change in the `Directionality` service provided by `@angular/cdk/bidi`.

This is problematic in cases where your Angular components rely on this service to update the UI when changing directionality.

**Comment by literalpie** [comment]
Hi, because @angular/cdk is an Angular-specific package, it wouldn't make sense for this addon to include that library in order to make them work together out of the box. However, it is possible to make the two work together. See [this repo](https://github.com/literalpie/angular-cdk-sb-addon-rtl-example) for an example.
